---
title: "Peer Review Three"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---

```{r setup,include=FALSE}
library(flexdashboard)
library(tidyverse)
library(plotly)
library(shiny)

dat<-read_csv(url("https://www.dropbox.com/s/4ebgnkdhhxo5rac/cel_volden_wiseman%20_coursera.csv?raw=1"))

dat$Party<-recode(dat$dem,'1'="Democrat",'0'="Republican")


#######HINT: for Chart D, you'll need to set the height of the renderPlot, using the height argument. Try a value of 750.

#####some data management functions are already included. You need to add the visualization functions.

```


Page 1
======

### Chart A


```{r}
df<-dat %>% 
  drop_na() %>% 
  filter(year>1979) %>% 
  group_by(year,Party) %>% 
  summarise(passed=sum(all_pass))
ggplot(data=df, aes(x=year, y=passed, fill=Party))+geom_area()+labs(x="All Bills Passed", y="Year", title="Number of Bills Passed Since 1980")+scale_fill_manual(values=c("Blue", "Red"))

```

Page 2 {data-orientation=columns}
=================================

Column 
-------------------------------------

### Chart B

```{r}
g<-dat %>%
  drop_na() %>%
  filter(congress == 110) %>%
  ggplot(aes(x = votepct, y = all_pass)) + geom_smooth(aes(color=Party))+ geom_point(aes(color=Party))+
  labs(x = "Vote Pct.", y = "All Pass", title = "Passage and Vote Pct., 110th Congress") +
  scale_color_manual(values = c("blue", "red"))
ggplotly(g)

```

Column 
-------------------------------------

### Chart C

```{r}
g<-dat%>%
  drop_na()%>%
  filter(congress==110) %>%
  ggplot(aes(x=dwnom1, y=all_pass, color=Party))+geom_point()+geom_smooth()+labs(x = "DW. Nominate", y = "All Pass", title = "Passage and Ideology, 110th Congress") +
  scale_color_manual(values = c("blue", "red"))
ggplotly(g)
```

Page 3 
===========

Input{.sidebar}
----------------------------------------------------------------


```{r}
selectInput(inputId="states", label="State", selected=dat$st_name, choices=dat$st_name ,multiple = TRUE)
```

Column{data-height=750}
----------------------------------------------------------------



### Chart D

```{r}

####hint: this figure uses selectInput with the multiple option set to true and with the options set up so that all states are initially selected.

renderPlot(dat %>%

        filter(congress==110 & st_name %in% input$states) %>%

        drop_na() %>%

        group_by(st_name) %>%

        summarise(passed=sum(all_pass)) %>%

        ggplot(aes(x=passed,y=st_name))+

        geom_bar(stat = "identity")+

        labs(x="Total Bills Passed Per State",y="State Name",title="Total Bills Passed by State Delegations, 110th Congress")

)

```

